---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        name: âœ… Check yaml files
      - id: check-toml
        name: âœ… Check toml files
      - id: check-ast
        name: âœ… Check files are valid python
      - id: check-docstring-first
        name: âœ… Check docstrings first
      - id: debug-statements
        name: âœ… Check debug statements
      - id: end-of-file-fixer
        name: â®  Fix end of files
      - id: trailing-whitespace
        name: â®  Trailing whitespace
      - id: no-commit-to-branch
        name: ğŸ›‘ No commit to master branch
        args:
          - --branch=master
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        name: ğŸ¶ Ruff Check
      - id: ruff-format
        name: ğŸ¶ Ruff Format
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        name: âœ… Black Format
        args:
          - --safe
          - --quiet
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        name: âœ… Check code for proper spelling
        args: []
        exclude_types: [csv, json]
        additional_dependencies:
          - tomli
  - repo: local
    hooks:
      - id: mypy
        name: ğŸ† Type checking with mypy
        entry: script/run-in-env.sh mypy
        language: script
        types: [python]
        require_serial: true
        files: ^pypaperless/.+\.py$
      - id: pylint
        name: ğŸŒŸ Rating code with pylint
        entry: script/run-in-env.sh pylint -j 0
        language: script
        types: [python]
        files: ^pypaperless/.+\.py$
