---
name: Pre-commit auto-update

on:
  schedule:
    - cron: "0 0 * * 1"

env:
  DEFAULT_PYTHON: "3.11"

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Checkout code
        uses: actions/checkout@v4.1.1
      - name: ğŸ Setup Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: ğŸš§ Install pre-commit
        run: pip install pre-commit
      - name: ğŸš§ Run pre-commit autoupdate
        run: pre-commit autoupdate
      - name: ğŸ…¿ï¸ Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/pre-commit-autoupdate
          title: Auto-update pre-commit hooks
          commit-message: Auto-update pre-commit hooks
          body: |
            Update versions of tools in pre-commit
            configs to latest version
          labels: dependencies, auto, no-stale
